routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('product', ProductController::class);

Route::resource('gallery', GalleryController::class);
Route::get('/product/{id}/gallery', [ProductController::class, 'gallery'])->name('product.gallery');

Route::resource('transaction', TransactionController::class);
Route::get('/transaction/{id}/status', [TransactionController::class, 'status'])->name('transaction.status');

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Gallery;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'type',
        'description',
        'price',
        'slug',
        'quantity',
    ];

    public function gallery()
    {
        return $this->hasMany(Gallery::class);
    }
}

app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function all(Request $request)
    {
        $id = $request->input('id');
        $limit = $request->input('limit', 6);
        $slug = $request->input('slug');
        $name = $request->input('name');
        $type = $request->input('type');
        $price_from = $request->input('price_from');
        $price_to = $request->input('price_to');

        // getAll
        $product = Product::with('gallery');

        // berdasarkan ID
        if($id){
            $product = Product::with('gallery')->find($id);

            if($product){
                return ResponseFormatter::success($product, 'Data produk berhasil diambil');
            }else{
                return ResponseFormatter::error(null, 'Data produk tidak ada', 404);
            }
        }

        // berdasarkan SLUG
        if($slug){
            $product = Product::with('gallery')->where('slug', $slug)->first();

            if($product){
                return ResponseFormatter::success($product, 'Data produk berhasil diambil');
            }else{
                return ResponseFormatter::error(null, 'Data produk tidak ada', 404);
            }
        }

        // berdasarkan NAME
        if($name){
            $product->where('name', 'like', '%' . $name . '%');
        }

        // berdasarkan TYPE
        if($type){
            $product->where('type', 'like', '%' . $type . '%');
        }

        // berdasarkan PRICE FROM
        if($price_from){
            $product->where('price_from', '>=', $price_from);
        }

        // berdasarkan PRICE TO
        if($price_to){
            $product->where('price_to', '<=', $price_to);
        }

        // Jika data list ditemukan, maka akan return success
        if($product->count() > 0){
            return ResponseFormatter::success(
                $product->paginate($limit),
                'Data list produk berhasil diambil'
            );
        }else{
            return ResponseFormatter::error(
                null,
                'Data list produk tidak ada',
                404
            );
        }
        
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gallery;
use App\Models\Product;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->get();
        return view('pages.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $data = $request->all();
        $data['slug'] = Str::slug($request->name);

        Product::create($data);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Product::findOrFail($id);
        return view('pages.products.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $data = $request->all();
        $data['slug'] = Str::slug($request->name);

        $item = Product::findOrFail($id);
        $item->update($data);
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Product::findOrFail($id);
        $item->delete();

        Gallery::where('product_id', $id)->delete();
        return redirect()->route('product.index');
    }

    public function gallery($id)
    {
        $items = Gallery::where('product_id', $id)->latest()->get();
        return view('pages.products.gallery', compact('items'));
    }
}

resources/views/pages/products/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="card">
            <div class="card-header">
                <strong>Tambah Barang</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('product.store') }}" method="POST">
                    @csrf
                    {{-- name --}}
                    <div class="form-group">
                        <label for="name" class="form-control-label">Nama Barang</label>
                        <input type="text" name="name" value="{{ old('name') }}" class="form-control 
                            @error('name')
                                is-invalid
                            @enderror"
                        />
                        @error('name')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- type --}}
                    <div class="form-group">
                        <label for="type" class="form-control-label">Tipe Barang</label>
                        <input type="text" name="type" value="{{ old('type') }}" class="form-control 
                            @error('type')
                                is-invalid
                            @enderror"
                        />
                        @error('type')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Description --}}
                    <div class="form-group">
                        <label for="description" class="form-control-label">Deskripsi Barang</label>
                        <textarea name="description" class="ckeditor form-control 
                            @error('description')
                                is-invalid
                            @enderror">
                            {{ old('description') }}
                        </textarea>
                        @error('description')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Price --}}
                    <div class="form-group">
                        <label for="price" class="form-control-label">Harga Barang</label>
                        <input type="number" name="price" value="{{ old('price') }}" class="form-control 
                            @error('price')
                                is-invalid
                            @enderror"
                        />
                        @error('price')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Quantity --}}
                    <div class="form-group">
                        <label for="quantity" class="form-control-label">Stok Barang</label>
                        <input type="number" name="quantity" value="{{ old('quantity') }}" class="form-control 
                            @error('quantity')
                                is-invalid
                            @enderror"
                        />
                        @error('quantity')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- TOMBOL SUBMIT --}}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">
                            Tambah Barang
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/products/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="card">
            <div class="card-header">
                <strong>Ubah Barang</strong>
                <small>{{ $item->name }}</small>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('product.update', $item->id) }}" method="POST">
                    @csrf
                    @method('put')
                    {{-- name --}}
                    <div class="form-group">
                        <label for="name" class="form-control-label">Nama Barang</label>
                        <input type="text" name="name" value="{{ old('name') ? old('name') : $item->name }}" class="form-control 
                            @error('name')
                                is-invalid
                            @enderror"
                        />
                        @error('name')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- type --}}
                    <div class="form-group">
                        <label for="type" class="form-control-label">Tipe Barang</label>
                        <input type="text" name="type" value="{{ old('type') ? old('type') : $item->type }}" class="form-control 
                            @error('type')
                                is-invalid
                            @enderror"
                        />
                        @error('type')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Description --}}
                    <div class="form-group">
                        <label for="description" class="form-control-label">Deskripsi Barang</label>
                        <textarea name="description" class="ckeditor form-control 
                            @error('description')
                                is-invalid
                            @enderror">
                            {{ old('description') ? old('description') : $item->description }}
                        </textarea>
                        @error('description')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Price --}}
                    <div class="form-group">
                        <label for="price" class="form-control-label">Harga Barang</label>
                        <input type="number" name="price" value="{{ old('price') ? old('price') : $item->price }}" class="form-control 
                            @error('price')
                                is-invalid
                            @enderror"
                        />
                        @error('price')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Quantity --}}
                    <div class="form-group">
                        <label for="quantity" class="form-control-label">Stok Barang</label>
                        <input type="number" name="quantity" value="{{ old('quantity') ? old('quantity') : $item->quantity }}" class="form-control 
                            @error('quantity')
                                is-invalid
                            @enderror"
                        />
                        @error('quantity')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- TOMBOL SUBMIT --}}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">
                            Ubah Barang
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/products/gallery.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="orders">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="box-title">Gallery Photo</h4>
                        </div>
                        <div class="card-body--">
                            <div class="table-stats order-table ov-h">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nama Barang</th>
                                            <th>Photo</th>
                                            <th>Default</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($items as $item)    
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->product->name }}</td>
                                            <td>
                                                <img src="{{ url($item->photo) }}">
                                            </td>
                                            <td>{{ $item->is_default ? 'Ya' : 'Tidak' }}</td>
                                            <td>
                                                <form action="{{ route('gallery.destroy', $item->id) }}" class="d-inline" type="submit" method="POST">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center text-muted"><i>Maaf, data kosong</i></td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/products/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="orders">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="box-title">Daftar Barang</h4>
                        </div>
                        <div class="card-body--">
                            <div class="table-stats order-table ov-h">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Type</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($products as $product)    
                                        <tr>
                                            <td>{{ $product->id }}</td>
                                            <td>{{ $product->name }}</td>
                                            <td>{{ $product->type }}</td>
                                            <td>${{ $product->price }}</td>
                                            <td>{{ $product->quantity }}</td>
                                            <td>
                                                <a href="{{ route('product.gallery', $product->id) }}" class="btn btn-info btn-sm">
                                                    <i class="fa fa-picture-o"></i>
                                                </a>
                                                <a href="{{ route('product.edit', $product->id) }}" class="btn btn-primary btn-sm">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <form action="{{ route('product.destroy', $product->id) }}" class="d-inline" type="submit" method="POST">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center text-muted"><i>Maaf, data kosong</i></td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection