routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('product', ProductController::class);

Route::resource('gallery', GalleryController::class);
Route::get('/product/{id}/gallery', [ProductController::class, 'gallery'])->name('product.gallery');

Route::resource('transaction', TransactionController::class);
Route::get('/transaction/{id}/status', [TransactionController::class, 'status'])->name('transaction.status');

require __DIR__.'/auth.php';

app/Http/Controllers/API/TransactionController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Transaction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TransactionController extends Controller
{
    public function get(Request $request, $id)
    {
        $product = Transaction::with(['detail.product'])->find($id);

        if($product){
            return ResponseFormatter::success($product, 'Data transaksi berhasil diambil');
        }else{
            return ResponseFormatter::error(null, 'Data transaksi tidak ada', 404);
        }
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaction;
use Illuminate\Http\Request;
use App\Models\TransactionDetail;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Transaction::all();
        return view('pages.transactions.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Transaction::findOrFail($id);
        return view('pages.transactions.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Transaction::findOrFail($id);
        return view('pages.transactions.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $item = Transaction::findOrFail($id);
        $item->update($data);
        return redirect()->route('transaction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Transaction::findOrFail($id);
        $item->delete();
        $detail = TransactionDetail::where('transaction_id', $id)->delete();

        return redirect()->route('transaction.index');
    }

    public function status(Request $request, $id)
    {
        $request->validate([
            'status' => 'required|in:PENDING,SUCCESS,FAILED',
        ]);

        $item = Transaction::findOrFail($id);
        $item->transaction_status = $request->status;
        $item->save();
        return redirect()->route('transaction.index');
    }
}

resources/views/pages/transactions/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="card">
            <div class="card-header">
                <strong>Ubah Data Transaksi</strong>
                <small>{{ $item->name }}</small>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('transaction.update', $item->id) }}" method="POST">
                    @csrf
                    @method('put')
                    {{-- name --}}
                    <div class="form-group">
                        <label for="name" class="form-control-label">Nama Pemesan</label>
                        <input type="text" name="name" value="{{ old('name') ? old('name') : $item->name }}" class="form-control 
                            @error('name')
                                is-invalid
                            @enderror"
                        />
                        @error('name')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- email --}}
                    <div class="form-group">
                        <label for="email" class="form-control-label">Tipe Barang</label>
                        <input type="email" name="email" value="{{ old('email') ? old('email') : $item->email }}" class="form-control 
                            @error('email')
                                is-invalid
                            @enderror"
                        />
                        @error('address')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Number --}}
                    <div class="form-group">
                        <label for="number" class="form-control-label">Nomor HP</label>
                        <input type="number" name="number" value="{{ old('number') ? old('number') : $item->number }}" class="form-control 
                            @error('number')
                                is-invalid
                            @enderror"
                        />
                        @error('number')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Address --}}
                    <div class="form-group">
                        <label for="address" class="form-control-label">Alamat Pemesan</label>
                        <textarea name="address" class="ckeditor form-control 
                            @error('address')
                                is-invalid
                            @enderror">
                            {{ old('address') ? old('address') : $item->address }}
                        </textarea>
                        @error('address')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- TOMBOL SUBMIT --}}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">
                            Ubah Barang
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/transactions/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="orders">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="box-title">Daftar Transaksi Masuk</h4>
                        </div>
                        <div class="card-body--">
                            <div class="table-stats order-table ov-h">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Nomor</th>
                                            <th>Total Transaksi</th>
                                            <th>Status Transaksi</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($items as $item)    
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->number }}</td>
                                            <td>${{ $item->transaction_total }}</td>
                                            <td>
                                                @if ($item->transaction_status == 'PENDING')
                                                    <span class="badge badge-info">
                                                @elseif($item->transaction_status == 'SUCCESS')
                                                    <span class="badge badge-success">
                                                @elseif($item->transaction_status == 'FAILED')
                                                    <span class="badge badge-danger">
                                                @else
                                                    <span>
                                                @endif
                                                    {{ $item->transaction_status }}
                                                    </span>
                                            </td>
                                            <td>
                                                <a href="#detailTransaction" 
                                                    data-remote="{{ route('transaction.show', $item->id) }}"
                                                    data-toggle="modal"
                                                    data-target="#detailTransaction"
                                                    data-title="Detail Transaction {{ $item->uuid }}"
                                                    class="btn btn-info btn-sm">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                                <a href="{{ route('transaction.edit', $item->id) }}" class="btn btn-primary btn-sm">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <form action="{{ route('transaction.destroy', $item->id) }}" class="d-inline" type="submit" method="POST">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center text-muted"><i>Maaf, data kosong</i></td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/transactions/show.blade.php
<table class="table table-bordered">
    <tr>
        <th>Nama</th>
        <td>{{ $item->name }}</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>{{ $item->email }}</td>
    </tr>
    <tr>
        <th>Nomor</th>
        <td>{{ $item->number }}</td>
    </tr>
    <tr>
        <th>Alamat</th>
        <td>{!! $item->address !!}</td>
    </tr>
    <tr>
        <th>Total Transaksi</th>
        <td>{{ $item->transaction_total }}</td>
    </tr>
    <tr>
        <th>Status Transaksi</th>
        <td>{{ $item->transaction_status }}</td>
    </tr>
    <tr>
        <th>Pembelian Produk</th>
        <td>
            <table class="table table-bordered">
                <tr>
                    <th>Nama</th>
                    <th>Tipe</th>
                    <th>Harga</th>
                </tr>
                @foreach ($item->detail as $detail)
                    <tr>
                        <td>{{ $detail->product->name }}</td>
                        <td>{{ $detail->product->type }}</td>
                        <td>${{ $detail->product->price }}</td>
                    </tr>
                @endforeach
            </table>
        </td>
    </tr>
</table>

<div class="row">
    <div class="col-4">
        <a href="{{ route('transaction.status', $item->id) }}?status=SUCCESS" class="btn btn-success btn-block">
            <i class="fa fa-check"></i> Set Sukses
        </a>
    </div>
    <div class="col-4">
        <a href="{{ route('transaction.status', $item->id) }}?status=FAILED" class="btn btn-danger btn-block">
            <i class="fa fa-times"></i> Set Failed
        </a>
    </div>
    <div class="col-4">
        <a href="{{ route('transaction.status', $item->id) }}?status=PENDING" class="btn btn-secondary btn-block">
            <i class="fa fa-spinner"></i> Set Pending
        </a>
    </div>
</div>