routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('product', ProductController::class);

Route::resource('gallery', GalleryController::class);
Route::get('/product/{id}/gallery', [ProductController::class, 'gallery'])->name('product.gallery');

Route::resource('transaction', TransactionController::class);
Route::get('/transaction/{id}/status', [TransactionController::class, 'status'])->name('transaction.status');

require __DIR__.'/auth.php';

app/Models/Gallery.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Gallery extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'product_id',
        'photo',
        'is_default'
    ];

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function getPhotoAttribute($value)
    {
        return url('storage/' . $value);
    }
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gallery;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Requests\GalleryRequest;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Gallery::latest()->get();
        return view('pages.galleries.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();
        return view('pages.galleries.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GalleryRequest $request)
    {
        $data = $request->all();
        $data['photo'] = $request->file('photo')->store(
            'assets/product', 'public'
        );

        Gallery::create($data);
        return redirect()->route('gallery.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Gallery::findOrFail($id);
        $item->delete();

        return redirect()->route('gallery.index');
    }
}

resources/views/pages/galleries/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="card">
            <div class="card-header">
                <strong>Tambah Foto Barang</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('gallery.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    {{-- name product --}}
                    <div class="form-group">
                        <label for="name" class="form-control-label">Nama F Barang</label>
                        <select name="product_id" class="form-control @error('product_id') is-invalid @enderror">
                            @foreach ($products as $product)
                                <option value="{{ $product->id }}">{{ $product->name }}</option>
                            @endforeach
                        </select>
                        @error('product_id')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Photo --}}
                    <div class="form-group">
                        <label for="photo" class="form-control-label">Foto Barang</label>
                        <input type="file" name="photo" required value="{{ old('photo') }}" accept="image/*" class="form-control
                            @error('foto')
                                is-invalid
                            @enderror"
                        />
                        @error('photo')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Is Default --}}
                    <div class="form-group">
                        <label for="is_default" class="form-control-label">Jadikan Photo Default</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_default" value="1" id="is_default-yes" checked>
                            <label class="form-check-label" for="is_default-yes">
                                Ya
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_default" value="0" id="is_default-no">
                            <label class="form-check-label" for="is_default-no">
                                Tidak
                            </label>
                        </div>
                        @error('is_default')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- TOMBOL SUBMIT --}}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">
                            Tambah Barang
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/galleries/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="card">
            <div class="card-header">
                <strong>Ubah Barang</strong>
                <small>{{ $item->name }}</small>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('product.update', $item->id) }}" method="POST">
                    @csrf
                    @method('put')
                    {{-- name --}}
                    <div class="form-group">
                        <label for="name" class="form-control-label">Nama Barang</label>
                        <input type="text" name="name" value="{{ old('name') ? old('name') : $item->name }}" class="form-control 
                            @error('name')
                                is-invalid
                            @enderror"
                        />
                        @error('name')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- type --}}
                    <div class="form-group">
                        <label for="type" class="form-control-label">Tipe Barang</label>
                        <input type="text" name="type" value="{{ old('type') ? old('type') : $item->type }}" class="form-control 
                            @error('type')
                                is-invalid
                            @enderror"
                        />
                        @error('type')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Description --}}
                    <div class="form-group">
                        <label for="description" class="form-control-label">Deskripsi Barang</label>
                        <textarea name="description" class="ckeditor form-control 
                            @error('description')
                                is-invalid
                            @enderror">
                            {{ old('description') ? old('description') : $item->description }}
                        </textarea>
                        @error('description')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Price --}}
                    <div class="form-group">
                        <label for="price" class="form-control-label">Harga Barang</label>
                        <input type="number" name="price" value="{{ old('price') ? old('price') : $item->price }}" class="form-control 
                            @error('price')
                                is-invalid
                            @enderror"
                        />
                        @error('price')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- Quantity --}}
                    <div class="form-group">
                        <label for="quantity" class="form-control-label">Stok Barang</label>
                        <input type="number" name="quantity" value="{{ old('quantity') ? old('quantity') : $item->quantity }}" class="form-control 
                            @error('quantity')
                                is-invalid
                            @enderror"
                        />
                        @error('quantity')
                            <div class="text-muted">{{ $message }}</div>
                        @enderror
                    </div>
                    {{-- TOMBOL SUBMIT --}}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">
                            Ubah Barang
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/galleries/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <div class="orders">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="box-title">Daftar Foto Barang</h4>
                        </div>
                        <div class="card-body--">
                            <div class="table-stats order-table ov-h">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nama Barang</th>
                                            <th>Photo</th>
                                            <th>Default</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($items as $item)    
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->product->name }}</td>
                                            <td>
                                                <img src="{{ url($item->photo) }}">
                                            </td>
                                            <td>{{ $item->is_default ? 'Ya' : 'Tidak' }}</td>
                                            <td>
                                                <form action="{{ route('gallery.destroy', $item->id) }}" class="d-inline" type="submit" method="POST">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center text-muted"><i>Maaf, data kosong</i></td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection